### ISSUE TITLE
Book rating bug

### ISSUE THREAD

**Issue by akaanuzman** [seyityahya/book_tracking_system#6]
<img width="1912" alt="Screenshot 2024-05-21 at 19 44 32" src="https://github.com/seyityahya/book_tracking_system/assets/55639112/66bf667b-7f49-433c-a16c-533e9772f98c">

Buradaki devreden sayıda olan ratingleri ya yukarı ya aşağı yuvarlayalım ya da sadece virgülden sonra bir ya da iki basamak gösterelim @seyityahya

**Comment by seyityahya** [comment]
virgülden sonra 1 sayı olması mantıklı gibi
